# Generated by Django 6.0.1 on 2026-02-02 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('platform', models.CharField(help_text='e.g. LinkedIn, Indeed, Company Website', max_length=100)),
                ('job_url', models.URLField(blank=True, help_text='Job ads link', null=True)),
                ('applied_at', models.DateField(blank=True, help_text='Date the application was submitted', null=True)),
                ('match_sore', models.IntegerField(choices=[(1, "I applied because I'm desperate"), (2, 'hm... not sure about this'), (3, 'Fit some criteria, worth a try'), (4, "It's a match!"), (5, 'The perfect dream job')], default=1, help_text='How well do you think this job suits you')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted')], default='saved', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
