# Generated by Django 6.0.1 on 2026-02-09 05:51

import applications.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_applicationstatushistory_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="job_url",
            field=applications.models.LongURLField(
                blank=True, help_text="Job ads link", null=True
            ),
        ),
    ]
